# Colección de ejercicios de Numpy

## 1 - Importa el paquete con el nombre "np".

`pista: import … as …`

In [ ]:
import numpy as np

## 2 - Imprime la versión instalada.

`pista: np.__version__, np.show_config`

In [ ]:
print(np.__version__)

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

## 3 - Crea un vector de nulos de tamaño 10.

`pista: np.zeros`

In [ ]:
vector_ceros = np.zeros(10)
print(vector_ceros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## 4 - Encontrar el tamaño en memoria de un array.

`pista: size, itemsize`

In [ ]:
# Crear un array de ejemplo
array_ejemplo = np.zeros(10)

# Calcular el tamaño en memoria
tamaño_memoria = array_ejemplo.size * array_ejemplo.itemsize
print(f"El tamaño en memoria del array es: {tamaño_memoria} bytes")

800 bytes


## 5 - Cree un vector nulo de tamaño 10 pero el quinto valor tiene de valor 1.

`pista: array[...]`

In [ ]:
vector_ceros_quinto_uno = np.zeros(10)
vector_ceros_quinto_uno[4] = 1
print(vector_ceros_quinto_uno)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


## 6 - Cree un vector con valores que van de 10 a 49.

`pista: arange`


In [ ]:
vector_10_49 = np.arange(10, 50)
print(vector_10_49)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


## 7 - Invierta un vector (el primer elemento se convierte en el último).

`pista: array[::-1]`

In [2]:
vector_invertido = vector_10_49[::-1]
print(vector_invertido)

NameError: name 'vector_10_49' is not defined

## 8 Cree una matriz de 3x3 con valores que van de 0 a 8.

`pista: reshape`

In [ ]:
matriz_3x3 = np.arange(9).reshape(3, 3)
print(matriz_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 9 - Encuentre los índices de elementos distintos de cero de `[7,5,0,0,2,1]`.

`pista: np.nonzero`

In [ ]:
array = np.array([7, 5, 0, 0, 2, 1])
indices_no_cero = np.nonzero(array)
print(indices_no_cero)

[7 5 2 1]


## 10 - Crear una matriz de identidad de 3x3.

`pista: np.eye`


In [ ]:
matriz_identidad_3x3 = np.eye(3)
print(matriz_identidad_3x3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 11 - Crear una matriz de 3x3x3 con valores aleatorios.

`pista: np.random.random`


In [ ]:
matriz_3x3x3_aleatoria = np.random.random((3, 3, 3))
print(matriz_3x3x3_aleatoria)

[[[0.35207293 0.89415773 0.62532973]
  [0.13301884 0.86462149 0.39465788]
  [0.28855831 0.37398066 0.47512955]]

 [[0.52927166 0.62513965 0.24561969]
  [0.95589816 0.2262938  0.23984761]
  [0.22340742 0.8857309  0.17035688]]

 [[0.67012056 0.22328839 0.35466369]
  [0.19150674 0.91820885 0.33611808]
  [0.3535846  0.67263676 0.43112082]]]


## 12 - Cree una matriz de 10x10 con valores aleatorios y encuentre el mínimo y el máximo.

`pista: min, max`

In [ ]:
matriz_10x10_aleatoria = np.random.random((10, 10))
min_valor = matriz_10x10_aleatoria.min()
max_valor = matriz_10x10_aleatoria.max()
print(f"El valor mínimo es: {min_valor}")
print(f"El valor máximo es: {max_valor}")

0.0034959856900877995 0.9997015692774968


## 13 - Cree un vector aleatorio de tamaño 50 y encuentre el valor medio.

`pista: mean`

In [ ]:
vector_aleatorio_50 = np.random.random(50)
valor_medio = np.mean(vector_aleatorio_50)
print(f"El valor medio es: {valor_medio}")

0.47461042880625665


## 14 - Cree una matriz de 6x6 con valores 1,2,3,4,5 justo debajo de la diagonal.

`pista: np.diag`

In [ ]:
matriz_6x6 = np.diag(1 + np.arange(5), k=-1)
print(matriz_6x6)

[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]]


## 15 - Considere una matriz de formas (4,5,6), ¿cuál es el índice (x,y,z) del elemento número 57?

`pista: np.unravel_index`

In [ ]:
# Crear una matriz de formas (4,5,6)
matriz = np.arange(4*5*6).reshape(4, 5, 6)

# Encontrar el índice (x, y, z) del elemento número 57
indice = np.unravel_index(57, matriz.shape)
print(f"El índice del elemento número 57 es: {indice}")


(1, 4, 2)


## 16 - Normalice una matriz aleatoria de 10x10.

`pista: (x - mean) / std`

In [ ]:
# Crear una matriz aleatoria de 10x10
matriz_10x10 = np.random.random((10, 10))

# Normalizar la matriz
media = np.mean(matriz_10x10)
desviacion_estandar = np.std(matriz_10x10)
matriz_normalizada = (matriz_10x10 - media) / desviacion_estandar

print(matriz_normalizada)

[[-1.92721617e+00  9.77238397e-01  1.81505886e+00  1.40341296e+00
   4.09230230e-01 -2.86380369e-01  5.10387687e-01 -1.00800034e+00
  -3.35965939e-01  4.31973516e-01]
 [-4.14391586e-01  1.47452903e+00 -1.07206486e+00  1.22587157e+00
  -6.23658120e-01 -1.35009663e+00  7.88885310e-02  1.11636303e+00
  -7.42146499e-01 -1.51043474e+00]
 [ 2.35672241e-01  1.51978667e-01 -5.90617738e-02 -9.79490419e-01
  -7.99035530e-01  1.53416621e+00 -1.47475001e+00 -1.35911359e+00
  -3.02560433e-01  9.30220419e-01]
 [-5.61344907e-01 -1.00021343e+00  1.13122573e+00  1.01834765e+00
   6.07085114e-01 -1.79666358e+00 -1.49305117e+00 -1.66703842e-01
   7.67838388e-01  8.64725361e-01]
 [-2.05062981e-01  1.83440391e-03 -1.04795157e+00 -5.60584548e-01
  -1.37691458e-01  7.78334318e-01  3.05178996e-01 -1.15591882e+00
   5.38768051e-01  9.87465216e-01]
 [ 7.70714906e-01  1.72506886e+00  1.42358435e+00  1.22481366e+00
  -6.46865544e-01 -1.56812248e+00  1.31666665e+00  4.40423821e-01
  -1.57173135e+00 -3.31306906e-01

## 17 - Multiplique una matriz de 3x2 por una matriz de 2x5.

In [ ]:
# Crear una matriz de 3x2
matriz_3x2 = np.random.random((3, 2))

# Crear una matriz de 2x5
matriz_2x5 = np.random.random((2, 5))

# Multiplicar las matrices
resultado = np.dot(matriz_3x2, matriz_2x5)
print(resultado)

[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


[[19 22]
 [43 50]]
[[23 34]
 [31 46]]


## 18 - ¿Cómo encuentra valores comunes entre dos matrices?

`pista: np.intersect1d`


In [ ]:
# Crear dos matrices de ejemplo
matriz1 = np.random.randint(0, 10, 10)
matriz2 = np.random.randint(0, 10, 10)

# Encontrar valores comunes
valores_comunes = np.intersect1d(matriz1, matriz2)
print(f"Valores comunes: {valores_comunes}")

[0 0 6 7 0 9 7 3 2 9]
[0 8 9 8 0 2 0 1 8 7]
[0 2 7 9]


## 19 - ¿Cómo obtener las fechas de ayer, hoy y mañana?

`pista: np.datetime64, np.timedelta64`


In [ ]:
hoy = np.datetime64('today', 'D')
ayer = hoy - np.timedelta64(1, 'D')
mañana = hoy + np.timedelta64(1, 'D')

print(f"Ayer: {ayer}")
print(f"Hoy: {hoy}")
print(f"Mañana: {mañana}")

Hoy es 2022-06-05, ayer fue 2022-06-07 y mañana será 2022-06-06


## 20 - ¿Cómo obtener todas las fechas correspondientes al mes de septiembre de 2020?

`pista: np.arange(dtype=datetime64['D'])`

In [ ]:
fechas_septiembre_2020 = np.arange('2020-09', '2020-10', dtype='datetime64[D]')
print(fechas_septiembre_2020)

['2020-09-01' '2020-09-02' '2020-09-03' '2020-09-04' '2020-09-05'
 '2020-09-06' '2020-09-07' '2020-09-08' '2020-09-09' '2020-09-10'
 '2020-09-11' '2020-09-12' '2020-09-13' '2020-09-14' '2020-09-15'
 '2020-09-16' '2020-09-17' '2020-09-18' '2020-09-19' '2020-09-20'
 '2020-09-21' '2020-09-22' '2020-09-23' '2020-09-24' '2020-09-25'
 '2020-09-26' '2020-09-27' '2020-09-28' '2020-09-29' '2020-09-30']


## 21 - Extraiga la parte entera de una matriz aleatoria de números positivos usando 4 métodos diferentes.

`pista: %, np.floor, astype, np.trunc`

In [ ]:
# Crear una matriz aleatoria de números positivos
matriz_aleatoria = np.random.random((5, 5)) * 10
print("Matriz original:")
print(matriz_aleatoria)

# Método 1: Usando el operador de módulo
parte_entera_modulo = matriz_aleatoria // 1
print("\nParte entera usando operador de módulo:")
print(parte_entera_modulo)

# Método 2: Usando np.floor
parte_entera_floor = np.floor(matriz_aleatoria)
print("\nParte entera usando np.floor:")
print(parte_entera_floor)

# Método 3: Usando astype(int)
parte_entera_astype = matriz_aleatoria.astype(int)
print("\nParte entera usando astype(int):")
print(parte_entera_astype)

# Método 4: Usando np.trunc
parte_entera_trunc = np.trunc(matriz_aleatoria)
print("\nParte entera usando np.trunc:")
print(parte_entera_trunc)

[4.46691822 1.38490394 2.59597445 2.10039777 6.47592481 9.27191582
 3.00311257 1.08708977 9.39885831 5.90046869]
[4. 1. 2. 2. 6. 9. 3. 1. 9. 5.]
[4. 1. 2. 2. 6. 9. 3. 1. 9. 5.]
[4. 1. 2. 2. 6. 9. 3. 1. 9. 5.]
[4 1 2 2 6 9 3 1 9 5]
[4. 1. 2. 2. 6. 9. 3. 1. 9. 5.]


## 22 - Cree una matriz de 10x10 con valores de fila que van de 0 a 9.

`pista: np.arange`

In [ ]:
matriz_10x10_filas = np.tile(np.arange(10), (10, 1))
print(matriz_10x10_filas)

[[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]]


## 23 - Cree un vector de tamaño 5 con valores que van de 0 a 1, ambos excluidos.

`pista: np.linspace`

In [51]:
vector_0_1_excluidos = np.linspace(0, 1, 6, endpoint=False)[1:]
print(vector_0_1_excluidos)

[0.16666667 0.33333333 0.5        0.66666667 0.83333333]


## 24 - Cree un vector aleatorio de tamaño 25 y ordénelo.

`pista: sort`

In [59]:
vector_aleatorio_25 = np.random.random(25)
vector_aleatorio_25_ordenado = np.sort(vector_aleatorio_25)
print(vector_aleatorio_25_ordenado)

[0.03316207 0.16277626 0.16430974 0.16721437 0.19528084 0.21098918
 0.40010633 0.40757855 0.42377496 0.42838823 0.44948954 0.55244695
 0.55986804 0.59714881 0.63775756 0.65577076 0.66104159 0.70032628
 0.71446331 0.77919721 0.79944571 0.84057554 0.90608252 0.91059094
 0.96634802]


## 25 - Sume un vector usando `np.add.reduce`.

In [60]:
# Crear un vector de ejemplo
vector_ejemplo = np.random.random(10)

# Sumar el vector usando np.add.reduce
suma_vector = np.add.reduce(vector_ejemplo)
print(f"La suma del vector es: {suma_vector}")

45

## 26 - Considere dos matrices aleatorias A y B, verifique si son iguales.

`pista: np.allclose, np.array_equal`

In [77]:
# Crear dos matrices aleatorias A y B
A = np.random.random((3, 3))
B = np.random.random((3, 3))

# Verificar si las matrices son iguales
son_iguales = np.array_equal(A, B)
print(f"Las matrices A y B son iguales: {son_iguales}")

[0 0 0 0 1]
[1 0 1 0 1]
False
False


## 27 - Cree un vector aleatorio de tamaño 25 y reemplace el valor máximo por 0.

`pista: argmax`


In [ ]:
# Crear un vector aleatorio de tamaño 25
vector_aleatorio_25 = np.random.random(25)

# Reemplazar el valor máximo por 0
vector_aleatorio_25[vector_aleatorio_25.argmax()] = 0
print(vector_aleatorio_25)

[0.01791447 0.89274845 0.07780698 0.59020409 0.34921659 0.48297902
 0.10589555 0.44398151 0.75114015 0.95186396 0.07414586 0.28576626
 0.56284085 0.56096044 0.56298931 0.32226905 0.77730745 0.33032758
 0.77637948 0.05671296 0.08633789 0.90503662 0.14791726 0.
 0.40295987]


## 28 - ¿Cómo imprimir todos los valores de una matriz?

`pista: np.set_printoptions`

In [80]:
# Configurar las opciones de impresión para mostrar todos los valores de la matriz
np.set_printoptions(threshold=np.inf)

# Crear una matriz de ejemplo
matriz_ejemplo = np.random.random((5, 5))

# Imprimir todos los valores de la matriz
print(matriz_ejemplo)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


## 29 - ¿Cómo encontrar el valor más cercano, a un escalar dado, en un vector?

`pista: argmin`


In [ ]:
# Crear un vector de ejemplo
vector_ejemplo = np.random.random(10) * 100
print("Vector de ejemplo:", vector_ejemplo)

# Escalar dado
escalar_dado = 50

# Encontrar el valor más cercano
valor_mas_cercano = vector_ejemplo[np.abs(vector_ejemplo - escalar_dado).argmin()]
print(f"El valor más cercano a {escalar_dado} es: {valor_mas_cercano}")

## 30 - ¿Cómo convertir una matriz `float` (32 bits) en tipo `int` (32 bits)?

`pista: view and [:] =`

In [ ]:
# Crear una matriz float de 32 bits de ejemplo
matriz_float32 = np.random.random((5, 5)).astype(np.float32)
print("Matriz float32 original:")
print(matriz_float32)

# Convertir la matriz a tipo int32
matriz_int32 = matriz_float32.astype(np.int32)
print("\nMatriz convertida a int32:")
print(matriz_int32)

[34 36 30 55 98 66 29 70 58 93]


## 31 - ¿Cuál es el equivalente de `enumerate` para matrices en `numpy`?

`pista: np.ndenumerate, np.ndindex`

In [ ]:
# Crear una matriz de ejemplo
matriz_ejemplo = np.random.random((3, 3))
print("Matriz original:")
print(matriz_ejemplo)

# Usar np.ndenumerate para enumerar elementos
print("\nUsando np.ndenumerate:")
for indice, valor in np.ndenumerate(matriz_ejemplo):
    print(indice, valor)

# Usar np.ndindex para enumerar índices
print("\nUsando np.ndindex:")
for indice in np.ndindex(matriz_ejemplo.shape):
    print(indice, matriz_ejemplo[indice])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(0, 3) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(1, 3) 7
(2, 0) 8
(2, 1) 9
(2, 2) 10
(2, 3) 11
(3, 0) 12
(3, 1) 13
(3, 2) 14
(3, 3) 15
(0, 0) 0
(0, 1) 1
(0, 2) 2
(0, 3) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(1, 3) 7
(2, 0) 8
(2, 1) 9
(2, 2) 10
(2, 3) 11
(3, 0) 12
(3, 1) 13
(3, 2) 14
(3, 3) 15


## 32 - Restar la media de cada fila a una matriz.

`pista: mean(axis=, keepdims=)`


In [88]:
# Crear una matriz de ejemplo
matriz_ejemplo = np.random.random((5, 5))
print("Matriz original:")
print(matriz_ejemplo)

# Restar la media de cada fila
media_filas = matriz_ejemplo.mean(axis=1, keepdims=True)
matriz_resta_media = matriz_ejemplo - media_filas
print("\nMatriz después de restar la media de cada fila:")
print(matriz_resta_media)

## 33 - ¿Cómo ordenar una matriz por la enésima columna?

`pista: argsort`

In [ ]:
# Crear una matriz de ejemplo
matriz_ejemplo = np.random.random((5, 5))
print("Matriz original:")
print(matriz_ejemplo)

# Ordenar la matriz por la enésima columna (por ejemplo, la tercera columna, índice 2)
n = 2
matriz_ordenada = matriz_ejemplo[matriz_ejemplo[:, n].argsort()]
print(f"\nMatriz ordenada por la columna {n}:")
print(matriz_ordenada)

[[4 5 7]
 [1 2 9]
 [5 7 3]]
[[1 2 9]
 [4 5 7]
 [5 7 3]]


## 34 - ¿Cómo saber si una matriz 2D tiene columnas nulas?

`pista: any, ~`


In [3]:
# Crear una matriz de ejemplo
matriz_ejemplo = np.random.random((5, 5))
print("Matriz original:")
print(matriz_ejemplo)

# Verificar si alguna columna es completamente nula
columnas_nulas = ~matriz_ejemplo.any(axis=0)
print(f"\n¿La matriz tiene columnas nulas?: {columnas_nulas.any()}")
print(f"Columnas nulas: {columnas_nulas}")

NameError: name 'np' is not defined

## 35 - Encuentre el valor más cercano de un valor dado en una matriz.

`pista: np.abs, argmin, flat`


In [ ]:
# Crear una matriz de ejemplo
matriz_ejemplo = np.random.random((5, 5)) * 100
print("Matriz de ejemplo:")
print(matriz_ejemplo)

# Valor dado
valor_dado = 50

# Encontrar el valor más cercano
valor_mas_cercano = matriz_ejemplo.flat[np.abs(matriz_ejemplo - valor_dado).argmin()]
print(f"El valor más cercano a {valor_dado} es: {valor_mas_cercano}")